version: '3.8'

services:
  room-service:
    build: ./room
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo-room
    networks:
      - app-network

  reservation-service:
    build: ./reservation
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo-reservation
    networks:
      - app-network

  auth-service:
    build: ./auth
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo-auth
    networks:
      - app-network

  mongo-room:
    image: mongo
    networks:
      - app-network

  mongo-reservation:
    image: mongo
    networks:
      - app-network

  mongo-auth:
    image: mongo
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - app-network

  gateway:
    build:
      context: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - room-service
      - reservation-service
      - auth-service
    environment:
      AUTH_SERVICE_HOST=auth-service
      AUTH_SERVICE_PORT=3000
      RESERVATION_SERVICE_HOST=reservation-service
      RESERVATION_SERVICE_PORT=3000
      ROOM_SERVICE_HOST=room-service
      ROOM_SERVICE_PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
