version: '3.8'

services:
  room-service:
    build: ./room
    ports:
      - "3001:3004"
    environment:
      - PORT=3004
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_VHOST=my_vhost
      - MONGO_HOST=mongo-room
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin
    depends_on:
      - mongo-room
      - rabbitmq
    networks:
      - app-network

  reservation-service:
    build: ./reservation
    ports:
      - "3002:3005"
    environment:
      - PORT=3005
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_VHOST=my_vhost
      - MONGO_HOST=mongo-room
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin
    depends_on:
      - mongo-reservation
      - rabbitmq
    networks:
      - app-network

  auth-service:
    build: ./auth
    ports:
      - "3003:3006"
    environment:
      - PORT=3006
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - JWT_SECRET=your_jwt_secret_key
      - RABBITMQ_VHOST=my_vhost
      - MONGO_HOST=mongo-room
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin
    depends_on:
      - mongo-auth
      - rabbitmq
    networks:
      - app-network

  mongo-room:
    image: mongo
    networks:
      - app-network

  mongo-reservation:
    image: mongo
    networks:
      - app-network

  mongo-auth:
    image: mongo
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - app-network

  gateway:
    build:
      context: ./gateway
    ports:
      - "3004:3007"
    depends_on:
      - room-service
      - reservation-service
      - auth-service
    environment:
      AUTH_SERVICE_HOST: auth-service
      AUTH_SERVICE_PORT: 3006
      RESERVATION_SERVICE_HOST: reservation-service
      RESERVATION_SERVICE_PORT: 3005
      ROOM_SERVICE_HOST: room-service
      ROOM_SERVICE_PORT: 3004
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
